# Generated by Django 6.0.4 on 2026-04-16 22:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('estado_disponibilidad', models.CharField(choices=[('disponible', 'Disponible'), ('en_despacho', 'En despacho'), ('mantencion', 'Mantención'), ('fuera_servicio', 'Fuera de servicio')], default='disponible', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InsumoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=100)),
                ('stock_total', models.IntegerField()),
                ('stock_minimo', models.IntegerField(default=0)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('condicion_paciente', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RolPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('totp_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ims_backend.rolpersonal')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_origen', models.CharField(max_length=255)),
                ('direccion_destino', models.CharField(blank=True, max_length=255)),
                ('descripcion_llamado', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido en control'), ('asignado', 'Asignado a equipo'), ('en_ruta_paciente', 'En ruta al paciente'), ('paciente_recogido', 'Paciente recogido'), ('en_ruta_hospital', 'En ruta al hospital'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='recibido', max_length=30)),
                ('fecha_llamado', models.DateTimeField(auto_now_add=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('ambulancia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ims_backend.ambulancia')),
                ('asignado_por', models.ForeignKey(help_text='Usuario de control que asignó el despacho', on_delete=django.db.models.deletion.PROTECT, related_name='despachos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_despacho', models.CharField(max_length=255)),
                ('hora_salida', models.DateTimeField()),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('sello_electronico', models.TextField(blank=True, help_text='Hash de integridad', null=True)),
                ('estado_sello', models.CharField(default='Pendiente', max_length=20)),
                ('ambulancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ims_backend.ambulancia')),
                ('despacho', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atencion', to='ims_backend.despacho')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_backend.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_s3_key', models.CharField(help_text='Ruta del archivo dentro del bucket S3', max_length=500)),
                ('archivo_hash', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('firma_s3_key', models.CharField(blank=True, help_text='Ruta de la firma .sig en S3', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atencion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='ims_backend.atencion')),
            ],
        ),
        migrations.CreateModel(
            name='DespachoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='ims_backend.despacho')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ims_backend.grupopersonal')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInsumoAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=50)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_utilizados', to='ims_backend.atencion')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ims_backend.insumomedico')),
            ],
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_usuario', models.CharField(help_text='RUT duplicado para preservar trazabilidad si el usuario se elimina', max_length=12)),
                ('descripcion', models.TextField(help_text="Ej: 'Administró 500mg de paracetamol vía oral'")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('atencion', models.ForeignKey(help_text='Atención a la que pertenece esta acción', on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='ims_backend.atencion')),
                ('usuario', models.ForeignKey(help_text='Personal que ejecutó la acción', on_delete=django.db.models.deletion.PROTECT, related_name='acciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('despacho', 'Nuevo despacho'), ('reasignacion', 'Reasignación'), ('alerta_stock', 'Stock bajo mínimo'), ('sistema', 'Sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('url_embebida', models.CharField(blank=True, help_text='Link a Google Maps u otro', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims_backend.despacho')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ims_backend.grupopersonal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('presion_sistolica', models.IntegerField(blank=True, null=True)),
                ('presion_diastolica', models.IntegerField(blank=True, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('saturacion_oxigeno', models.IntegerField(blank=True, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='ims_backend.atencion')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SuscritosAGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, help_text='Es null cuando esta activo en el grupo', null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupo_nombre', to='ims_backend.grupopersonal')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupo_personal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketCredencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('observaciones_resolucion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resuelto_por', models.ForeignKey(blank=True, help_text='Usuario control que resolvió el ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_resueltos', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_credencial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='despacho',
            index=models.Index(fields=['estado', 'fecha_llamado'], name='ims_backend_estado_82daca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='despachopersonal',
            unique_together={('despacho', 'grupo')},
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['atencion', 'timestamp'], name='ims_backend_atencio_24f707_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['usuario', 'timestamp'], name='ims_backend_usuario_88a1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['destinatario'], name='ims_backend_destina_cb3824_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['rut'], name='ims_backend_rut_968341_idx'),
        ),
        migrations.AddIndex(
            model_name='suscritosagrupo',
            index=models.Index(fields=['grupo', 'fecha_entrada'], name='ims_backend_grupo_i_fb5dca_idx'),
        ),
        migrations.AddIndex(
            model_name='suscritosagrupo',
            index=models.Index(fields=['grupo', 'fecha_salida'], name='ims_backend_grupo_i_fe7ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='suscritosagrupo',
            index=models.Index(fields=['grupo', 'personal'], name='ims_backend_grupo_i_584f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcredencial',
            index=models.Index(fields=['estado', 'created_at'], name='ims_backend_estado_fec8fe_idx'),
        ),
    ]
