# Generated by Django 6.0.4 on 2026-04-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='comuna',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
