# Generated by Django 6.0.4 on 2026-05-16 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='paciente',
        ),
        migrations.AddField(
            model_name='despacho',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despacho_paciente', to='ims_backend.paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='condicion_paciente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
