# Generated by Django 6.0.4 on 2026-05-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_backend', '0002_remove_atencion_paciente_despacho_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='direccion_despacho',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
