/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/AdminDashboard` | `/AdminDashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/Despachos` | `/Despachos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/Inventario` | `/Inventario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/Panel` | `/Panel`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/RegistrarPaciente` | `/RegistrarPaciente`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/recuperacion` | `/recuperacion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/Despachos` | `/Despachos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/RegistrarAtencion` | `/RegistrarAtencion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/UserDashboard` | `/UserDashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/detalledespacho/[id]` | `/detalledespacho/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/AdminDashboard` | `/AdminDashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/Despachos` | `/Despachos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/Inventario` | `/Inventario`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/Panel` | `/Panel`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/RegistrarPaciente` | `/RegistrarPaciente`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/recuperacion` | `/recuperacion`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(user)'}/Despachos` | `/Despachos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(user)'}/RegistrarAtencion` | `/RegistrarAtencion`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(user)'}/UserDashboard` | `/UserDashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/detalledespacho/[id]` | `/detalledespacho/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/AdminDashboard${`?${string}` | `#${string}` | ''}` | `/AdminDashboard${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/Despachos${`?${string}` | `#${string}` | ''}` | `/Despachos${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/Inventario${`?${string}` | `#${string}` | ''}` | `/Inventario${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/Panel${`?${string}` | `#${string}` | ''}` | `/Panel${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/RegistrarPaciente${`?${string}` | `#${string}` | ''}` | `/RegistrarPaciente${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/recuperacion${`?${string}` | `#${string}` | ''}` | `/recuperacion${`?${string}` | `#${string}` | ''}` | `${'/(user)'}/Despachos${`?${string}` | `#${string}` | ''}` | `/Despachos${`?${string}` | `#${string}` | ''}` | `${'/(user)'}/RegistrarAtencion${`?${string}` | `#${string}` | ''}` | `/RegistrarAtencion${`?${string}` | `#${string}` | ''}` | `${'/(user)'}/UserDashboard${`?${string}` | `#${string}` | ''}` | `/UserDashboard${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/AdminDashboard` | `/AdminDashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/Despachos` | `/Despachos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/Inventario` | `/Inventario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/Panel` | `/Panel`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/RegistrarPaciente` | `/RegistrarPaciente`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/recuperacion` | `/recuperacion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/Despachos` | `/Despachos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/RegistrarAtencion` | `/RegistrarAtencion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/UserDashboard` | `/UserDashboard`; params?: Router.UnknownInputParams; } | `${'/(admin)'}/detalledespacho/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/detalledespacho/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(admin)'}/detalledespacho/[id]` | `/detalledespacho/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
